# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adamj/Documents/C/CodeWizard2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adamj/Documents/C/CodeWizard2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adamj/Documents/C/CodeWizard2/CMakeFiles /home/adamj/Documents/C/CodeWizard2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adamj/Documents/C/CodeWizard2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libvterm

# Build rule for target.
libvterm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libvterm
.PHONY : libvterm

# fast build rule for target.
libvterm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/build
.PHONY : libvterm/fast

#=============================================================================
# Target rules for targets named CodeWizard

# Build rule for target.
CodeWizard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CodeWizard
.PHONY : CodeWizard

# fast build rule for target.
CodeWizard/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/build
.PHONY : CodeWizard/fast

#=============================================================================
# Target rules for targets named sioclient

# Build rule for target.
sioclient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sioclient
.PHONY : sioclient

# fast build rule for target.
sioclient/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sioclient-build/CMakeFiles/sioclient.dir/build.make _deps/sioclient-build/CMakeFiles/sioclient.dir/build
.PHONY : sioclient/fast

#=============================================================================
# Target rules for targets named sioclient_tls

# Build rule for target.
sioclient_tls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sioclient_tls
.PHONY : sioclient_tls

# fast build rule for target.
sioclient_tls/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sioclient-build/CMakeFiles/sioclient_tls.dir/build.make _deps/sioclient-build/CMakeFiles/sioclient_tls.dir/build
.PHONY : sioclient_tls/fast

_deps/libvterm_src-src/src/encoding.o: _deps/libvterm_src-src/src/encoding.c.o
.PHONY : _deps/libvterm_src-src/src/encoding.o

# target to build an object file
_deps/libvterm_src-src/src/encoding.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/encoding.c.o
.PHONY : _deps/libvterm_src-src/src/encoding.c.o

_deps/libvterm_src-src/src/encoding.i: _deps/libvterm_src-src/src/encoding.c.i
.PHONY : _deps/libvterm_src-src/src/encoding.i

# target to preprocess a source file
_deps/libvterm_src-src/src/encoding.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/encoding.c.i
.PHONY : _deps/libvterm_src-src/src/encoding.c.i

_deps/libvterm_src-src/src/encoding.s: _deps/libvterm_src-src/src/encoding.c.s
.PHONY : _deps/libvterm_src-src/src/encoding.s

# target to generate assembly for a file
_deps/libvterm_src-src/src/encoding.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/encoding.c.s
.PHONY : _deps/libvterm_src-src/src/encoding.c.s

_deps/libvterm_src-src/src/keyboard.o: _deps/libvterm_src-src/src/keyboard.c.o
.PHONY : _deps/libvterm_src-src/src/keyboard.o

# target to build an object file
_deps/libvterm_src-src/src/keyboard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/keyboard.c.o
.PHONY : _deps/libvterm_src-src/src/keyboard.c.o

_deps/libvterm_src-src/src/keyboard.i: _deps/libvterm_src-src/src/keyboard.c.i
.PHONY : _deps/libvterm_src-src/src/keyboard.i

# target to preprocess a source file
_deps/libvterm_src-src/src/keyboard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/keyboard.c.i
.PHONY : _deps/libvterm_src-src/src/keyboard.c.i

_deps/libvterm_src-src/src/keyboard.s: _deps/libvterm_src-src/src/keyboard.c.s
.PHONY : _deps/libvterm_src-src/src/keyboard.s

# target to generate assembly for a file
_deps/libvterm_src-src/src/keyboard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/keyboard.c.s
.PHONY : _deps/libvterm_src-src/src/keyboard.c.s

_deps/libvterm_src-src/src/mouse.o: _deps/libvterm_src-src/src/mouse.c.o
.PHONY : _deps/libvterm_src-src/src/mouse.o

# target to build an object file
_deps/libvterm_src-src/src/mouse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/mouse.c.o
.PHONY : _deps/libvterm_src-src/src/mouse.c.o

_deps/libvterm_src-src/src/mouse.i: _deps/libvterm_src-src/src/mouse.c.i
.PHONY : _deps/libvterm_src-src/src/mouse.i

# target to preprocess a source file
_deps/libvterm_src-src/src/mouse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/mouse.c.i
.PHONY : _deps/libvterm_src-src/src/mouse.c.i

_deps/libvterm_src-src/src/mouse.s: _deps/libvterm_src-src/src/mouse.c.s
.PHONY : _deps/libvterm_src-src/src/mouse.s

# target to generate assembly for a file
_deps/libvterm_src-src/src/mouse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/mouse.c.s
.PHONY : _deps/libvterm_src-src/src/mouse.c.s

_deps/libvterm_src-src/src/parser.o: _deps/libvterm_src-src/src/parser.c.o
.PHONY : _deps/libvterm_src-src/src/parser.o

# target to build an object file
_deps/libvterm_src-src/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/parser.c.o
.PHONY : _deps/libvterm_src-src/src/parser.c.o

_deps/libvterm_src-src/src/parser.i: _deps/libvterm_src-src/src/parser.c.i
.PHONY : _deps/libvterm_src-src/src/parser.i

# target to preprocess a source file
_deps/libvterm_src-src/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/parser.c.i
.PHONY : _deps/libvterm_src-src/src/parser.c.i

_deps/libvterm_src-src/src/parser.s: _deps/libvterm_src-src/src/parser.c.s
.PHONY : _deps/libvterm_src-src/src/parser.s

# target to generate assembly for a file
_deps/libvterm_src-src/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/parser.c.s
.PHONY : _deps/libvterm_src-src/src/parser.c.s

_deps/libvterm_src-src/src/pen.o: _deps/libvterm_src-src/src/pen.c.o
.PHONY : _deps/libvterm_src-src/src/pen.o

# target to build an object file
_deps/libvterm_src-src/src/pen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/pen.c.o
.PHONY : _deps/libvterm_src-src/src/pen.c.o

_deps/libvterm_src-src/src/pen.i: _deps/libvterm_src-src/src/pen.c.i
.PHONY : _deps/libvterm_src-src/src/pen.i

# target to preprocess a source file
_deps/libvterm_src-src/src/pen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/pen.c.i
.PHONY : _deps/libvterm_src-src/src/pen.c.i

_deps/libvterm_src-src/src/pen.s: _deps/libvterm_src-src/src/pen.c.s
.PHONY : _deps/libvterm_src-src/src/pen.s

# target to generate assembly for a file
_deps/libvterm_src-src/src/pen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/pen.c.s
.PHONY : _deps/libvterm_src-src/src/pen.c.s

_deps/libvterm_src-src/src/screen.o: _deps/libvterm_src-src/src/screen.c.o
.PHONY : _deps/libvterm_src-src/src/screen.o

# target to build an object file
_deps/libvterm_src-src/src/screen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/screen.c.o
.PHONY : _deps/libvterm_src-src/src/screen.c.o

_deps/libvterm_src-src/src/screen.i: _deps/libvterm_src-src/src/screen.c.i
.PHONY : _deps/libvterm_src-src/src/screen.i

# target to preprocess a source file
_deps/libvterm_src-src/src/screen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/screen.c.i
.PHONY : _deps/libvterm_src-src/src/screen.c.i

_deps/libvterm_src-src/src/screen.s: _deps/libvterm_src-src/src/screen.c.s
.PHONY : _deps/libvterm_src-src/src/screen.s

# target to generate assembly for a file
_deps/libvterm_src-src/src/screen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/screen.c.s
.PHONY : _deps/libvterm_src-src/src/screen.c.s

_deps/libvterm_src-src/src/state.o: _deps/libvterm_src-src/src/state.c.o
.PHONY : _deps/libvterm_src-src/src/state.o

# target to build an object file
_deps/libvterm_src-src/src/state.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/state.c.o
.PHONY : _deps/libvterm_src-src/src/state.c.o

_deps/libvterm_src-src/src/state.i: _deps/libvterm_src-src/src/state.c.i
.PHONY : _deps/libvterm_src-src/src/state.i

# target to preprocess a source file
_deps/libvterm_src-src/src/state.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/state.c.i
.PHONY : _deps/libvterm_src-src/src/state.c.i

_deps/libvterm_src-src/src/state.s: _deps/libvterm_src-src/src/state.c.s
.PHONY : _deps/libvterm_src-src/src/state.s

# target to generate assembly for a file
_deps/libvterm_src-src/src/state.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/state.c.s
.PHONY : _deps/libvterm_src-src/src/state.c.s

_deps/libvterm_src-src/src/unicode.o: _deps/libvterm_src-src/src/unicode.c.o
.PHONY : _deps/libvterm_src-src/src/unicode.o

# target to build an object file
_deps/libvterm_src-src/src/unicode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/unicode.c.o
.PHONY : _deps/libvterm_src-src/src/unicode.c.o

_deps/libvterm_src-src/src/unicode.i: _deps/libvterm_src-src/src/unicode.c.i
.PHONY : _deps/libvterm_src-src/src/unicode.i

# target to preprocess a source file
_deps/libvterm_src-src/src/unicode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/unicode.c.i
.PHONY : _deps/libvterm_src-src/src/unicode.c.i

_deps/libvterm_src-src/src/unicode.s: _deps/libvterm_src-src/src/unicode.c.s
.PHONY : _deps/libvterm_src-src/src/unicode.s

# target to generate assembly for a file
_deps/libvterm_src-src/src/unicode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/unicode.c.s
.PHONY : _deps/libvterm_src-src/src/unicode.c.s

_deps/libvterm_src-src/src/vterm.o: _deps/libvterm_src-src/src/vterm.c.o
.PHONY : _deps/libvterm_src-src/src/vterm.o

# target to build an object file
_deps/libvterm_src-src/src/vterm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/vterm.c.o
.PHONY : _deps/libvterm_src-src/src/vterm.c.o

_deps/libvterm_src-src/src/vterm.i: _deps/libvterm_src-src/src/vterm.c.i
.PHONY : _deps/libvterm_src-src/src/vterm.i

# target to preprocess a source file
_deps/libvterm_src-src/src/vterm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/vterm.c.i
.PHONY : _deps/libvterm_src-src/src/vterm.c.i

_deps/libvterm_src-src/src/vterm.s: _deps/libvterm_src-src/src/vterm.c.s
.PHONY : _deps/libvterm_src-src/src/vterm.s

# target to generate assembly for a file
_deps/libvterm_src-src/src/vterm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvterm.dir/build.make CMakeFiles/libvterm.dir/_deps/libvterm_src-src/src/vterm.c.s
.PHONY : _deps/libvterm_src-src/src/vterm.c.s

application.o: application.cpp.o
.PHONY : application.o

# target to build an object file
application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/application.cpp.o
.PHONY : application.cpp.o

application.i: application.cpp.i
.PHONY : application.i

# target to preprocess a source file
application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/application.cpp.i
.PHONY : application.cpp.i

application.s: application.cpp.s
.PHONY : application.s

# target to generate assembly for a file
application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/application.cpp.s
.PHONY : application.cpp.s

asteroids.o: asteroids.cpp.o
.PHONY : asteroids.o

# target to build an object file
asteroids.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/asteroids.cpp.o
.PHONY : asteroids.cpp.o

asteroids.i: asteroids.cpp.i
.PHONY : asteroids.i

# target to preprocess a source file
asteroids.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/asteroids.cpp.i
.PHONY : asteroids.cpp.i

asteroids.s: asteroids.cpp.s
.PHONY : asteroids.s

# target to generate assembly for a file
asteroids.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/asteroids.cpp.s
.PHONY : asteroids.cpp.s

brokenstatemenu.o: brokenstatemenu.cpp.o
.PHONY : brokenstatemenu.o

# target to build an object file
brokenstatemenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/brokenstatemenu.cpp.o
.PHONY : brokenstatemenu.cpp.o

brokenstatemenu.i: brokenstatemenu.cpp.i
.PHONY : brokenstatemenu.i

# target to preprocess a source file
brokenstatemenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/brokenstatemenu.cpp.i
.PHONY : brokenstatemenu.cpp.i

brokenstatemenu.s: brokenstatemenu.cpp.s
.PHONY : brokenstatemenu.s

# target to generate assembly for a file
brokenstatemenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/brokenstatemenu.cpp.s
.PHONY : brokenstatemenu.cpp.s

button.o: button.cpp.o
.PHONY : button.o

# target to build an object file
button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/button.cpp.o
.PHONY : button.cpp.o

button.i: button.cpp.i
.PHONY : button.i

# target to preprocess a source file
button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/button.cpp.i
.PHONY : button.cpp.i

button.s: button.cpp.s
.PHONY : button.s

# target to generate assembly for a file
button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/button.cpp.s
.PHONY : button.cpp.s

chat.o: chat.cpp.o
.PHONY : chat.o

# target to build an object file
chat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/chat.cpp.o
.PHONY : chat.cpp.o

chat.i: chat.cpp.i
.PHONY : chat.i

# target to preprocess a source file
chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/chat.cpp.i
.PHONY : chat.cpp.i

chat.s: chat.cpp.s
.PHONY : chat.s

# target to generate assembly for a file
chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/chat.cpp.s
.PHONY : chat.cpp.s

checkbox.o: checkbox.cpp.o
.PHONY : checkbox.o

# target to build an object file
checkbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/checkbox.cpp.o
.PHONY : checkbox.cpp.o

checkbox.i: checkbox.cpp.i
.PHONY : checkbox.i

# target to preprocess a source file
checkbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/checkbox.cpp.i
.PHONY : checkbox.cpp.i

checkbox.s: checkbox.cpp.s
.PHONY : checkbox.s

# target to generate assembly for a file
checkbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/checkbox.cpp.s
.PHONY : checkbox.cpp.s

codeedit.o: codeedit.cpp.o
.PHONY : codeedit.o

# target to build an object file
codeedit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/codeedit.cpp.o
.PHONY : codeedit.cpp.o

codeedit.i: codeedit.cpp.i
.PHONY : codeedit.i

# target to preprocess a source file
codeedit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/codeedit.cpp.i
.PHONY : codeedit.cpp.i

codeedit.s: codeedit.cpp.s
.PHONY : codeedit.s

# target to generate assembly for a file
codeedit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/codeedit.cpp.s
.PHONY : codeedit.cpp.s

compare.o: compare.cpp.o
.PHONY : compare.o

# target to build an object file
compare.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/compare.cpp.o
.PHONY : compare.cpp.o

compare.i: compare.cpp.i
.PHONY : compare.i

# target to preprocess a source file
compare.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/compare.cpp.i
.PHONY : compare.cpp.i

compare.s: compare.cpp.s
.PHONY : compare.s

# target to generate assembly for a file
compare.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/compare.cpp.s
.PHONY : compare.cpp.s

contextmenu.o: contextmenu.cpp.o
.PHONY : contextmenu.o

# target to build an object file
contextmenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/contextmenu.cpp.o
.PHONY : contextmenu.cpp.o

contextmenu.i: contextmenu.cpp.i
.PHONY : contextmenu.i

# target to preprocess a source file
contextmenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/contextmenu.cpp.i
.PHONY : contextmenu.cpp.i

contextmenu.s: contextmenu.cpp.s
.PHONY : contextmenu.s

# target to generate assembly for a file
contextmenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/contextmenu.cpp.s
.PHONY : contextmenu.cpp.s

curler.o: curler.cpp.o
.PHONY : curler.o

# target to build an object file
curler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/curler.cpp.o
.PHONY : curler.cpp.o

curler.i: curler.cpp.i
.PHONY : curler.i

# target to preprocess a source file
curler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/curler.cpp.i
.PHONY : curler.cpp.i

curler.s: curler.cpp.s
.PHONY : curler.s

# target to generate assembly for a file
curler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/curler.cpp.s
.PHONY : curler.cpp.s

editor.o: editor.cpp.o
.PHONY : editor.o

# target to build an object file
editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/editor.cpp.o
.PHONY : editor.cpp.o

editor.i: editor.cpp.i
.PHONY : editor.i

# target to preprocess a source file
editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/editor.cpp.i
.PHONY : editor.cpp.i

editor.s: editor.cpp.s
.PHONY : editor.s

# target to generate assembly for a file
editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/editor.cpp.s
.PHONY : editor.cpp.s

filetree.o: filetree.cpp.o
.PHONY : filetree.o

# target to build an object file
filetree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/filetree.cpp.o
.PHONY : filetree.cpp.o

filetree.i: filetree.cpp.i
.PHONY : filetree.i

# target to preprocess a source file
filetree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/filetree.cpp.i
.PHONY : filetree.cpp.i

filetree.s: filetree.cpp.s
.PHONY : filetree.s

# target to generate assembly for a file
filetree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/filetree.cpp.s
.PHONY : filetree.cpp.s

helpmenu.o: helpmenu.cpp.o
.PHONY : helpmenu.o

# target to build an object file
helpmenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/helpmenu.cpp.o
.PHONY : helpmenu.cpp.o

helpmenu.i: helpmenu.cpp.i
.PHONY : helpmenu.i

# target to preprocess a source file
helpmenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/helpmenu.cpp.i
.PHONY : helpmenu.cpp.i

helpmenu.s: helpmenu.cpp.s
.PHONY : helpmenu.s

# target to generate assembly for a file
helpmenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/helpmenu.cpp.s
.PHONY : helpmenu.cpp.s

highlighter.o: highlighter.cpp.o
.PHONY : highlighter.o

# target to build an object file
highlighter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/highlighter.cpp.o
.PHONY : highlighter.cpp.o

highlighter.i: highlighter.cpp.i
.PHONY : highlighter.i

# target to preprocess a source file
highlighter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/highlighter.cpp.i
.PHONY : highlighter.cpp.i

highlighter.s: highlighter.cpp.s
.PHONY : highlighter.s

# target to generate assembly for a file
highlighter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/highlighter.cpp.s
.PHONY : highlighter.cpp.s

imageview.o: imageview.cpp.o
.PHONY : imageview.o

# target to build an object file
imageview.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/imageview.cpp.o
.PHONY : imageview.cpp.o

imageview.i: imageview.cpp.i
.PHONY : imageview.i

# target to preprocess a source file
imageview.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/imageview.cpp.i
.PHONY : imageview.cpp.i

imageview.s: imageview.cpp.s
.PHONY : imageview.s

# target to generate assembly for a file
imageview.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/imageview.cpp.s
.PHONY : imageview.cpp.s

label.o: label.cpp.o
.PHONY : label.o

# target to build an object file
label.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/label.cpp.o
.PHONY : label.cpp.o

label.i: label.cpp.i
.PHONY : label.i

# target to preprocess a source file
label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/label.cpp.i
.PHONY : label.cpp.i

label.s: label.cpp.s
.PHONY : label.s

# target to generate assembly for a file
label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/label.cpp.s
.PHONY : label.cpp.s

languageserverclient.o: languageserverclient.cpp.o
.PHONY : languageserverclient.o

# target to build an object file
languageserverclient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/languageserverclient.cpp.o
.PHONY : languageserverclient.cpp.o

languageserverclient.i: languageserverclient.cpp.i
.PHONY : languageserverclient.i

# target to preprocess a source file
languageserverclient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/languageserverclient.cpp.i
.PHONY : languageserverclient.cpp.i

languageserverclient.s: languageserverclient.cpp.s
.PHONY : languageserverclient.s

# target to generate assembly for a file
languageserverclient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/languageserverclient.cpp.s
.PHONY : languageserverclient.cpp.s

linenumbers.o: linenumbers.cpp.o
.PHONY : linenumbers.o

# target to build an object file
linenumbers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/linenumbers.cpp.o
.PHONY : linenumbers.cpp.o

linenumbers.i: linenumbers.cpp.i
.PHONY : linenumbers.i

# target to preprocess a source file
linenumbers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/linenumbers.cpp.i
.PHONY : linenumbers.cpp.i

linenumbers.s: linenumbers.cpp.s
.PHONY : linenumbers.s

# target to generate assembly for a file
linenumbers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/linenumbers.cpp.s
.PHONY : linenumbers.cpp.s

listbox.o: listbox.cpp.o
.PHONY : listbox.o

# target to build an object file
listbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/listbox.cpp.o
.PHONY : listbox.cpp.o

listbox.i: listbox.cpp.i
.PHONY : listbox.i

# target to preprocess a source file
listbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/listbox.cpp.i
.PHONY : listbox.cpp.i

listbox.s: listbox.cpp.s
.PHONY : listbox.s

# target to generate assembly for a file
listbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/listbox.cpp.s
.PHONY : listbox.cpp.s

lspdebug.o: lspdebug.cpp.o
.PHONY : lspdebug.o

# target to build an object file
lspdebug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/lspdebug.cpp.o
.PHONY : lspdebug.cpp.o

lspdebug.i: lspdebug.cpp.i
.PHONY : lspdebug.i

# target to preprocess a source file
lspdebug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/lspdebug.cpp.i
.PHONY : lspdebug.cpp.i

lspdebug.s: lspdebug.cpp.s
.PHONY : lspdebug.s

# target to generate assembly for a file
lspdebug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/lspdebug.cpp.s
.PHONY : lspdebug.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/main.cpp.s
.PHONY : main.cpp.s

mathwindow.o: mathwindow.cpp.o
.PHONY : mathwindow.o

# target to build an object file
mathwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/mathwindow.cpp.o
.PHONY : mathwindow.cpp.o

mathwindow.i: mathwindow.cpp.i
.PHONY : mathwindow.i

# target to preprocess a source file
mathwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/mathwindow.cpp.i
.PHONY : mathwindow.cpp.i

mathwindow.s: mathwindow.cpp.s
.PHONY : mathwindow.s

# target to generate assembly for a file
mathwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/mathwindow.cpp.s
.PHONY : mathwindow.cpp.s

md4c.o: md4c.c.o
.PHONY : md4c.o

# target to build an object file
md4c.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/md4c.c.o
.PHONY : md4c.c.o

md4c.i: md4c.c.i
.PHONY : md4c.i

# target to preprocess a source file
md4c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/md4c.c.i
.PHONY : md4c.c.i

md4c.s: md4c.c.s
.PHONY : md4c.s

# target to generate assembly for a file
md4c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/md4c.c.s
.PHONY : md4c.c.s

myrect.o: myrect.cpp.o
.PHONY : myrect.o

# target to build an object file
myrect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/myrect.cpp.o
.PHONY : myrect.cpp.o

myrect.i: myrect.cpp.i
.PHONY : myrect.i

# target to preprocess a source file
myrect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/myrect.cpp.i
.PHONY : myrect.cpp.i

myrect.s: myrect.cpp.s
.PHONY : myrect.s

# target to generate assembly for a file
myrect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/myrect.cpp.s
.PHONY : myrect.cpp.s

panel_holder.o: panel_holder.cpp.o
.PHONY : panel_holder.o

# target to build an object file
panel_holder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/panel_holder.cpp.o
.PHONY : panel_holder.cpp.o

panel_holder.i: panel_holder.cpp.i
.PHONY : panel_holder.i

# target to preprocess a source file
panel_holder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/panel_holder.cpp.i
.PHONY : panel_holder.cpp.i

panel_holder.s: panel_holder.cpp.s
.PHONY : panel_holder.s

# target to generate assembly for a file
panel_holder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/panel_holder.cpp.s
.PHONY : panel_holder.cpp.s

scrollbar.o: scrollbar.cpp.o
.PHONY : scrollbar.o

# target to build an object file
scrollbar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/scrollbar.cpp.o
.PHONY : scrollbar.cpp.o

scrollbar.i: scrollbar.cpp.i
.PHONY : scrollbar.i

# target to preprocess a source file
scrollbar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/scrollbar.cpp.i
.PHONY : scrollbar.cpp.i

scrollbar.s: scrollbar.cpp.s
.PHONY : scrollbar.s

# target to generate assembly for a file
scrollbar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/scrollbar.cpp.s
.PHONY : scrollbar.cpp.s

scrollnotify.o: scrollnotify.cpp.o
.PHONY : scrollnotify.o

# target to build an object file
scrollnotify.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/scrollnotify.cpp.o
.PHONY : scrollnotify.cpp.o

scrollnotify.i: scrollnotify.cpp.i
.PHONY : scrollnotify.i

# target to preprocess a source file
scrollnotify.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/scrollnotify.cpp.i
.PHONY : scrollnotify.cpp.i

scrollnotify.s: scrollnotify.cpp.s
.PHONY : scrollnotify.s

# target to generate assembly for a file
scrollnotify.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/scrollnotify.cpp.s
.PHONY : scrollnotify.cpp.s

settings.o: settings.cpp.o
.PHONY : settings.o

# target to build an object file
settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/settings.cpp.o
.PHONY : settings.cpp.o

settings.i: settings.cpp.i
.PHONY : settings.i

# target to preprocess a source file
settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/settings.cpp.i
.PHONY : settings.cpp.i

settings.s: settings.cpp.s
.PHONY : settings.s

# target to generate assembly for a file
settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/settings.cpp.s
.PHONY : settings.cpp.s

settingsmanager.o: settingsmanager.cpp.o
.PHONY : settingsmanager.o

# target to build an object file
settingsmanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/settingsmanager.cpp.o
.PHONY : settingsmanager.cpp.o

settingsmanager.i: settingsmanager.cpp.i
.PHONY : settingsmanager.i

# target to preprocess a source file
settingsmanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/settingsmanager.cpp.i
.PHONY : settingsmanager.cpp.i

settingsmanager.s: settingsmanager.cpp.s
.PHONY : settingsmanager.s

# target to generate assembly for a file
settingsmanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/settingsmanager.cpp.s
.PHONY : settingsmanager.cpp.s

tabs.o: tabs.cpp.o
.PHONY : tabs.o

# target to build an object file
tabs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/tabs.cpp.o
.PHONY : tabs.cpp.o

tabs.i: tabs.cpp.i
.PHONY : tabs.i

# target to preprocess a source file
tabs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/tabs.cpp.i
.PHONY : tabs.cpp.i

tabs.s: tabs.cpp.s
.PHONY : tabs.s

# target to generate assembly for a file
tabs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/tabs.cpp.s
.PHONY : tabs.cpp.s

terminal.o: terminal.cpp.o
.PHONY : terminal.o

# target to build an object file
terminal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/terminal.cpp.o
.PHONY : terminal.cpp.o

terminal.i: terminal.cpp.i
.PHONY : terminal.i

# target to preprocess a source file
terminal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/terminal.cpp.i
.PHONY : terminal.cpp.i

terminal.s: terminal.cpp.s
.PHONY : terminal.s

# target to generate assembly for a file
terminal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/terminal.cpp.s
.PHONY : terminal.cpp.s

terminalwidget.o: terminalwidget.cpp.o
.PHONY : terminalwidget.o

# target to build an object file
terminalwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/terminalwidget.cpp.o
.PHONY : terminalwidget.cpp.o

terminalwidget.i: terminalwidget.cpp.i
.PHONY : terminalwidget.i

# target to preprocess a source file
terminalwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/terminalwidget.cpp.i
.PHONY : terminalwidget.cpp.i

terminalwidget.s: terminalwidget.cpp.s
.PHONY : terminalwidget.s

# target to generate assembly for a file
terminalwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/terminalwidget.cpp.s
.PHONY : terminalwidget.cpp.s

terminalwidgettabbed.o: terminalwidgettabbed.cpp.o
.PHONY : terminalwidgettabbed.o

# target to build an object file
terminalwidgettabbed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/terminalwidgettabbed.cpp.o
.PHONY : terminalwidgettabbed.cpp.o

terminalwidgettabbed.i: terminalwidgettabbed.cpp.i
.PHONY : terminalwidgettabbed.i

# target to preprocess a source file
terminalwidgettabbed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/terminalwidgettabbed.cpp.i
.PHONY : terminalwidgettabbed.cpp.i

terminalwidgettabbed.s: terminalwidgettabbed.cpp.s
.PHONY : terminalwidgettabbed.s

# target to generate assembly for a file
terminalwidgettabbed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/terminalwidgettabbed.cpp.s
.PHONY : terminalwidgettabbed.cpp.s

text_renderer.o: text_renderer.cpp.o
.PHONY : text_renderer.o

# target to build an object file
text_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/text_renderer.cpp.o
.PHONY : text_renderer.cpp.o

text_renderer.i: text_renderer.cpp.i
.PHONY : text_renderer.i

# target to preprocess a source file
text_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/text_renderer.cpp.i
.PHONY : text_renderer.cpp.i

text_renderer.s: text_renderer.cpp.s
.PHONY : text_renderer.s

# target to generate assembly for a file
text_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/text_renderer.cpp.s
.PHONY : text_renderer.cpp.s

textedit.o: textedit.cpp.o
.PHONY : textedit.o

# target to build an object file
textedit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/textedit.cpp.o
.PHONY : textedit.cpp.o

textedit.i: textedit.cpp.i
.PHONY : textedit.i

# target to preprocess a source file
textedit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/textedit.cpp.i
.PHONY : textedit.cpp.i

textedit.s: textedit.cpp.s
.PHONY : textedit.s

# target to generate assembly for a file
textedit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/textedit.cpp.s
.PHONY : textedit.cpp.s

tinyfiledialogs.o: tinyfiledialogs.c.o
.PHONY : tinyfiledialogs.o

# target to build an object file
tinyfiledialogs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/tinyfiledialogs.c.o
.PHONY : tinyfiledialogs.c.o

tinyfiledialogs.i: tinyfiledialogs.c.i
.PHONY : tinyfiledialogs.i

# target to preprocess a source file
tinyfiledialogs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/tinyfiledialogs.c.i
.PHONY : tinyfiledialogs.c.i

tinyfiledialogs.s: tinyfiledialogs.c.s
.PHONY : tinyfiledialogs.s

# target to generate assembly for a file
tinyfiledialogs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/tinyfiledialogs.c.s
.PHONY : tinyfiledialogs.c.s

titlebar.o: titlebar.cpp.o
.PHONY : titlebar.o

# target to build an object file
titlebar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/titlebar.cpp.o
.PHONY : titlebar.cpp.o

titlebar.i: titlebar.cpp.i
.PHONY : titlebar.i

# target to preprocess a source file
titlebar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/titlebar.cpp.i
.PHONY : titlebar.cpp.i

titlebar.s: titlebar.cpp.s
.PHONY : titlebar.s

# target to generate assembly for a file
titlebar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/titlebar.cpp.s
.PHONY : titlebar.cpp.s

toast.o: toast.cpp.o
.PHONY : toast.o

# target to build an object file
toast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/toast.cpp.o
.PHONY : toast.cpp.o

toast.i: toast.cpp.i
.PHONY : toast.i

# target to preprocess a source file
toast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/toast.cpp.i
.PHONY : toast.cpp.i

toast.s: toast.cpp.s
.PHONY : toast.s

# target to generate assembly for a file
toast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/toast.cpp.s
.PHONY : toast.cpp.s

updatechecker.o: updatechecker.cpp.o
.PHONY : updatechecker.o

# target to build an object file
updatechecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/updatechecker.cpp.o
.PHONY : updatechecker.cpp.o

updatechecker.i: updatechecker.cpp.i
.PHONY : updatechecker.i

# target to preprocess a source file
updatechecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/updatechecker.cpp.i
.PHONY : updatechecker.cpp.i

updatechecker.s: updatechecker.cpp.s
.PHONY : updatechecker.s

# target to generate assembly for a file
updatechecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/updatechecker.cpp.s
.PHONY : updatechecker.cpp.s

widget.o: widget.cpp.o
.PHONY : widget.o

# target to build an object file
widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/widget.cpp.o
.PHONY : widget.cpp.o

widget.i: widget.cpp.i
.PHONY : widget.i

# target to preprocess a source file
widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/widget.cpp.i
.PHONY : widget.cpp.i

widget.s: widget.cpp.s
.PHONY : widget.s

# target to generate assembly for a file
widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/widget.cpp.s
.PHONY : widget.cpp.s

widgetchooser.o: widgetchooser.cpp.o
.PHONY : widgetchooser.o

# target to build an object file
widgetchooser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/widgetchooser.cpp.o
.PHONY : widgetchooser.cpp.o

widgetchooser.i: widgetchooser.cpp.i
.PHONY : widgetchooser.i

# target to preprocess a source file
widgetchooser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/widgetchooser.cpp.i
.PHONY : widgetchooser.cpp.i

widgetchooser.s: widgetchooser.cpp.s
.PHONY : widgetchooser.s

# target to generate assembly for a file
widgetchooser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/widgetchooser.cpp.s
.PHONY : widgetchooser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... CodeWizard"
	@echo "... libvterm"
	@echo "... sioclient"
	@echo "... sioclient_tls"
	@echo "... _deps/libvterm_src-src/src/encoding.o"
	@echo "... _deps/libvterm_src-src/src/encoding.i"
	@echo "... _deps/libvterm_src-src/src/encoding.s"
	@echo "... _deps/libvterm_src-src/src/keyboard.o"
	@echo "... _deps/libvterm_src-src/src/keyboard.i"
	@echo "... _deps/libvterm_src-src/src/keyboard.s"
	@echo "... _deps/libvterm_src-src/src/mouse.o"
	@echo "... _deps/libvterm_src-src/src/mouse.i"
	@echo "... _deps/libvterm_src-src/src/mouse.s"
	@echo "... _deps/libvterm_src-src/src/parser.o"
	@echo "... _deps/libvterm_src-src/src/parser.i"
	@echo "... _deps/libvterm_src-src/src/parser.s"
	@echo "... _deps/libvterm_src-src/src/pen.o"
	@echo "... _deps/libvterm_src-src/src/pen.i"
	@echo "... _deps/libvterm_src-src/src/pen.s"
	@echo "... _deps/libvterm_src-src/src/screen.o"
	@echo "... _deps/libvterm_src-src/src/screen.i"
	@echo "... _deps/libvterm_src-src/src/screen.s"
	@echo "... _deps/libvterm_src-src/src/state.o"
	@echo "... _deps/libvterm_src-src/src/state.i"
	@echo "... _deps/libvterm_src-src/src/state.s"
	@echo "... _deps/libvterm_src-src/src/unicode.o"
	@echo "... _deps/libvterm_src-src/src/unicode.i"
	@echo "... _deps/libvterm_src-src/src/unicode.s"
	@echo "... _deps/libvterm_src-src/src/vterm.o"
	@echo "... _deps/libvterm_src-src/src/vterm.i"
	@echo "... _deps/libvterm_src-src/src/vterm.s"
	@echo "... application.o"
	@echo "... application.i"
	@echo "... application.s"
	@echo "... asteroids.o"
	@echo "... asteroids.i"
	@echo "... asteroids.s"
	@echo "... brokenstatemenu.o"
	@echo "... brokenstatemenu.i"
	@echo "... brokenstatemenu.s"
	@echo "... button.o"
	@echo "... button.i"
	@echo "... button.s"
	@echo "... chat.o"
	@echo "... chat.i"
	@echo "... chat.s"
	@echo "... checkbox.o"
	@echo "... checkbox.i"
	@echo "... checkbox.s"
	@echo "... codeedit.o"
	@echo "... codeedit.i"
	@echo "... codeedit.s"
	@echo "... compare.o"
	@echo "... compare.i"
	@echo "... compare.s"
	@echo "... contextmenu.o"
	@echo "... contextmenu.i"
	@echo "... contextmenu.s"
	@echo "... curler.o"
	@echo "... curler.i"
	@echo "... curler.s"
	@echo "... editor.o"
	@echo "... editor.i"
	@echo "... editor.s"
	@echo "... filetree.o"
	@echo "... filetree.i"
	@echo "... filetree.s"
	@echo "... helpmenu.o"
	@echo "... helpmenu.i"
	@echo "... helpmenu.s"
	@echo "... highlighter.o"
	@echo "... highlighter.i"
	@echo "... highlighter.s"
	@echo "... imageview.o"
	@echo "... imageview.i"
	@echo "... imageview.s"
	@echo "... label.o"
	@echo "... label.i"
	@echo "... label.s"
	@echo "... languageserverclient.o"
	@echo "... languageserverclient.i"
	@echo "... languageserverclient.s"
	@echo "... linenumbers.o"
	@echo "... linenumbers.i"
	@echo "... linenumbers.s"
	@echo "... listbox.o"
	@echo "... listbox.i"
	@echo "... listbox.s"
	@echo "... lspdebug.o"
	@echo "... lspdebug.i"
	@echo "... lspdebug.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mathwindow.o"
	@echo "... mathwindow.i"
	@echo "... mathwindow.s"
	@echo "... md4c.o"
	@echo "... md4c.i"
	@echo "... md4c.s"
	@echo "... myrect.o"
	@echo "... myrect.i"
	@echo "... myrect.s"
	@echo "... panel_holder.o"
	@echo "... panel_holder.i"
	@echo "... panel_holder.s"
	@echo "... scrollbar.o"
	@echo "... scrollbar.i"
	@echo "... scrollbar.s"
	@echo "... scrollnotify.o"
	@echo "... scrollnotify.i"
	@echo "... scrollnotify.s"
	@echo "... settings.o"
	@echo "... settings.i"
	@echo "... settings.s"
	@echo "... settingsmanager.o"
	@echo "... settingsmanager.i"
	@echo "... settingsmanager.s"
	@echo "... tabs.o"
	@echo "... tabs.i"
	@echo "... tabs.s"
	@echo "... terminal.o"
	@echo "... terminal.i"
	@echo "... terminal.s"
	@echo "... terminalwidget.o"
	@echo "... terminalwidget.i"
	@echo "... terminalwidget.s"
	@echo "... terminalwidgettabbed.o"
	@echo "... terminalwidgettabbed.i"
	@echo "... terminalwidgettabbed.s"
	@echo "... text_renderer.o"
	@echo "... text_renderer.i"
	@echo "... text_renderer.s"
	@echo "... textedit.o"
	@echo "... textedit.i"
	@echo "... textedit.s"
	@echo "... tinyfiledialogs.o"
	@echo "... tinyfiledialogs.i"
	@echo "... tinyfiledialogs.s"
	@echo "... titlebar.o"
	@echo "... titlebar.i"
	@echo "... titlebar.s"
	@echo "... toast.o"
	@echo "... toast.i"
	@echo "... toast.s"
	@echo "... updatechecker.o"
	@echo "... updatechecker.i"
	@echo "... updatechecker.s"
	@echo "... widget.o"
	@echo "... widget.i"
	@echo "... widget.s"
	@echo "... widgetchooser.o"
	@echo "... widgetchooser.i"
	@echo "... widgetchooser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

